name: CI

on:
  push:

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci

  lint-typecheck-format:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:nocache --workspaces --if-present
      - run: npm run typecheck --workspaces --if-present
      - run: npm run prettier --workspaces --if-present

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node: ['14', '16', '18']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run test:ci --workspaces --if-present
