name: CI

on:
  push:

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'
          check-latest: true
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci

  lint-typecheck-format:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - name: install website dependencies
        working-directory: website
        run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run prettier

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node: ['18', '20']

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run test:ci
